# Generated by Django 4.0.3 on 2022-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0002_editorial_libro_editorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
                ('independiente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
                ('generacion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
                ('num_horas', models.IntegerField()),
                ('genero', models.TextField(max_length=150)),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
