# Generated by Django 4.0.3 on 2022-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0004_remove_videojuego_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha_publicacion',
            field=models.DateField(default=0),
        ),
    ]
