# Generated by Django 4.0.3 on 2022-05-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0007_alter_videojuego_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='compania',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GameStore.compania'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='consola',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GameStore.consola'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
