# Generated by Django 4.0.3 on 2022-05-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0008_videojuego_compania_videojuego_consola_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='compania',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='consola',
        ),
        migrations.DeleteModel(
            name='Compania',
        ),
        migrations.DeleteModel(
            name='Consola',
        ),
    ]
