# Generated by Django 4.0.3 on 2022-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
                ('num_paginas', models.IntegerField()),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
    ]
