# Generated by Django 4.0.3 on 2022-03-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libreria.editorial'),
        ),
    ]
